name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        cd ./lr_3/tiny-database
        poetry install --no-root
    - name: Test with pytest
      run: |
        cd ./lr_3/tiny-database
        poetry run pytest --cov-fail-under=100
